jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    uses: actions/checkout@v1
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'a-file-here.xml'
        xpath: '//version'
    - name: Create Release
      uses: some-random/release-action@v1
      with:
        artifacts: 'another-file.zip'
        tag: ${{ steps.getxml.outputs.info }}
